<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Guneets-MacBook-Air.local" ignored="0" name="testTest" tests="13" failures="5" timestamp="2019-10-10T01:37:44 IST" time="10.301" errors="0">
  <testcase name="TestA" time="0.025" classname="com.test.sample.FunctionalSample1"/>
  <testcase name="TestB" time="0.013" classname="com.test.sample.FunctionalSample1">
    <failure type="java.lang.AssertionError" message="expected 3 but got 4 expected [4] but found [2]">
      <![CDATA[java.lang.AssertionError: expected 3 but got 4 expected [4] but found [2]
at com.test.sample.FunctionalSample1.TestB(FunctionalSample1.java:16)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TestB -->
  <testcase name="TestC" time="0.104" classname="com.test.sample.FunctionalSample1"/>
  <testcase name="TestD" time="0.001" classname="com.test.sample.FunctionalSample1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.test.sample.FunctionalSample1.TestD(FunctionalSample1.java:29)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TestD -->
  <testcase name="TestE" time="0.0" classname="com.test.sample.FunctionalSample1"/>
  <testcase name="TestF" time="0.001" classname="com.test.sample.FunctionalSample1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.test.sample.FunctionalSample1.TestF(FunctionalSample1.java:39)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TestF -->
  <testcase name="testCaseSkipException" time="0.0" classname="com.test.sample.FunctionalSample1">
    <skipped/>
  </testcase> <!-- testCaseSkipException -->
  <testcase name="dataProviderTest" time="0.0" classname="functional.FunctionalSample"/>
  <testcase name="dataProviderTest" time="0.001" classname="functional.FunctionalSample">
    <failure type="java.lang.AssertionError" message="expected [TestNGMetrics] but found [TestNG]">
      <![CDATA[java.lang.AssertionError: expected [TestNGMetrics] but found [TestNG]
at functional.FunctionalSample.dataProviderTest(FunctionalSample.java:42)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- dataProviderTest -->
  <testcase name="failingTest" time="0.0" classname="functional.FunctionalSample">
    <failure type="java.lang.AssertionError" message="expected [Metrics] but found [TestNG]">
      <![CDATA[java.lang.AssertionError: expected [Metrics] but found [TestNG]
at functional.FunctionalSample.failingTest(FunctionalSample.java:27)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- failingTest -->
  <testcase name="passingTest" time="0.0" classname="functional.FunctionalSample"/>
  <testcase name="passingTest1" time="0.001" classname="functional.FunctionalSample"/>
  <testcase name="skippingTest" time="0.0" classname="functional.FunctionalSample">
    <skipped/>
  </testcase> <!-- skippingTest -->
</testsuite> <!-- testTest -->
