<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Guneets-MacBook-Air.local" ignored="0" name="testTest" tests="7" failures="3" timestamp="2019-10-06T22:22:12 IST" time="0.42" errors="0">
  <testcase name="TestA" time="0.04" classname="com.test.sample.FunctionalSample1"/>
  <testcase name="TestB" time="0.008" classname="com.test.sample.FunctionalSample1">
    <failure type="java.lang.AssertionError" message="expected 3 but got 4 expected [4] but found [2]">
      <![CDATA[java.lang.AssertionError: expected 3 but got 4 expected [4] but found [2]
at com.test.sample.FunctionalSample1.TestB(FunctionalSample1.java:16)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- TestB -->
  <testcase name="TestC" time="0.113" classname="com.test.sample.FunctionalSample1"/>
  <testcase name="TestD" time="0.001" classname="com.test.sample.FunctionalSample1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.test.sample.FunctionalSample1.TestD(FunctionalSample1.java:29)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TestD -->
  <testcase name="TestE" time="0.0" classname="com.test.sample.FunctionalSample1"/>
  <testcase name="TestF" time="0.0" classname="com.test.sample.FunctionalSample1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.test.sample.FunctionalSample1.TestF(FunctionalSample1.java:39)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- TestF -->
  <testcase name="testCaseSkipException" time="0.002" classname="com.test.sample.FunctionalSample1">
    <skipped/>
  </testcase> <!-- testCaseSkipException -->
</testsuite> <!-- testTest -->
