<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Guneets-MacBook-Air.local" ignored="0" name="testTest" tests="5" failures="2" timestamp="2019-09-01T17:15:37 IST" time="0.103" errors="0">
  <testcase name="TestA" time="0.016" classname="com.test.sample.FunctionalSample1"/>
  <testcase name="TestB" time="0.006" classname="com.test.sample.FunctionalSample1">
    <failure type="java.lang.AssertionError" message="expected 3 but got 4 expected [4] but found [2]">
      <![CDATA[java.lang.AssertionError: expected 3 but got 4 expected [4] but found [2]
at com.test.sample.FunctionalSample1.TestB(FunctionalSample1.java:16)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- TestB -->
  <testcase name="TestC" time="0.001" classname="com.test.sample.FunctionalSample1"/>
  <testcase name="TestD" time="0.001" classname="com.test.sample.FunctionalSample1">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.test.sample.FunctionalSample1.TestD(FunctionalSample1.java:27)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- TestD -->
  <testcase name="TestE" time="0.0" classname="com.test.sample.FunctionalSample1"/>
</testsuite> <!-- testTest -->
